services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: kyrsach_web
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    ports:
      - "127.0.0.1:8000:8000"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: kyrsach_web
      DB_USER: postgres
      DB_PASSWORD: postgres
      SECRET_KEY: super_secret_coursework_key_2026
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "127.0.0.1:3000:80"
    depends_on:
      - backend

volumes:
  pgdata: